root: true                                                                      
                                                                                
env:                                                                            
  node: true                                                                    
                                                                                
parserOptions:                                                                  
  ecmaVersion: 7                                                                
                                                                                
rules:                                                                          
  eol-last: error                                                               
  eqeqeq: [warning, allow-null]                                                   
  indent: [error, 2, { SwitchCase: 1 }]                                         
  no-trailing-spaces: error                                                     
  no-unused-vars: [error, { vars: all, args: none, ignoreRestSiblings: true }]  
  semi: [error, always]    
