version: 2.0
jobs:
  lint:
    machine: 
      image: circleci/classic:201808-01
    steps:
      - checkout  
      - run: npm install eslint                                               
      - run: npm run lint                                                     
workflows:                                                                      
  version: 2
  build-and-test:                                                             
    jobs:                                                                     
      - lint: 
          filters:
            branches: 
              only: master
